### ISSUE TITLE
Why does the exported PSK contain newlines?

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-pnet#10]
In https://github.com/libp2p/go-libp2p-pnet/blob/master/generate.go#L25, a couple of *\n* are added to the exported PSK.
Now my exported PSK looks something like this:
```

/key/swarm/psk/1.0.0/
/base16/
7c1e1b5a7f4884455b6098029f7c358811d4826a0cd679723d5c1da5082d5595
```
I think it would be more convenient to have that on one line, i.e.
```
/key/swarm/psk/1.0.0/base16/7c1e1b5a7f4884455b6098029f7c358811d4826a0cd679723d5c1da5082d5595
```

**Comment by Kubuxu** [comment]
As it is human readable format for a `swarm.key` file in go-ipfs.

**Comment by Kubuxu** [comment]
It is also stacked multicodec, first multicodec explains the format, second the encodcing.

**Comment by marten-seemann** [comment]
Makes sense when reading from a file. Thanks.
