### ISSUE TITLE
go-crypto dependency has wrong dvcs-import

### ISSUE THREAD

**Issue by whyrusleeping** [libp2p/go-libp2p-pnet#20]
The go-crypto-dav import has its dvcs import in its package.json set to just davidlazaar/go-crypto. This breaks a thing i'm working on (and is incorrect)

**Comment by whyrusleeping** [comment]
This should not be possible, we should verify this in the publish step, or something.

cc @Kubuxu

**Comment by Kubuxu** [comment]
The dvcs import is correct: https://ipfs.io/ipfs/QmQur8VHmc276wJDRdU7KtR3qbA88Dov587DpBnzDbENuo/go-crypto-dav/package.json

**Comment by Kubuxu** [comment]
It is this package: https://github.com/davidlazar/go-crypto

**Comment by whyrusleeping** [comment]
@Kubuxu then why is the package path go-crypto-dav?

**Comment by Stebalien** [comment]
Because we already have a `go-crypto` package.
