### ISSUE TITLE
Questions on using this package

### ISSUE THREAD

**Issue by t-bast** [libp2p/go-libp2p-pnet#22]
Hey guys,

I feel the README is quite light ;) so I had to read the code to understand what this package does (and thus I might have gotten it wrong) and if I can use it in my project. I got here because the Protector interface states that it "secure(s) connections
so they can be only established with selected number of peers.". That's exactly what I want to implement: a way for people to create a private network on libp2p, specify who participates in the network and deny all connections from/to non-specified participants. I would also like to build dynamic add/removal of peers.

Reading the code in this repo, if I understand it correctly, it looks like it does the following:

- Generate a 32-bytes key that "identifies" the private network (needs to be shared securely with participants)
- Use salsa20 with this key to encrypt each connection

That means the network doesn't deny connections from non-participants right? Instead connections with non-participants would end up being garbage bytes because it would not decrypt properly, but outsiders could make us waste bandwidth by opening connections and sending garbage.

Moreover, I think there's no way of making the network easily dynamic. If you want to revoke someone's access to the private network, since that participant has the secret key your only choice is to bootstrap a new network with another key that you would not share with the participant you want to kick out. Or to rotate the key and somehow give the new one to everyone except the participant you wish to remove. Is my understanding correct?

Don't get me wrong, I'm not saying that this package doesn't do the right thing, I'm just trying to figure out if this package aims to do what I need or if I should work on another implementation of go-libp2p-interface-pnet that would suit my needs :).

**Comment by Stebalien** [comment]
> I feel the README is quite light

Yeah... it is.

--

> That means the network doesn't deny connections from non-participants right? Instead connections with non-participants would end up being garbage bytes because it would not decrypt properly, but outsiders could make us waste bandwidth by opening connections and sending garbage.

This package is designed to be layered over a security transport like secio or tls. This layer is expected to perform authenticated encryption and should kill any connection sending garbage.

> Moreover, I think there's no way of making the network easily dynamic. 

Yes, the only way to do this at the moment is to rekey.

---

FYI, this package was motivated by research groups, companies, etc. that want to run a private IPFS network composed of mostly trusted nodes.

**Comment by t-bast** [comment]
Cool thanks for the quick answer.
I think I'll work on a custom protector implementation that would be best suited for my needs (dynamic private networks). I'll check this repo regularly to see where it's going ;).

**Comment by Kubuxu** [comment]
@t-bast if you arrive at anything, it would be awesome if you show it to us.

**Comment by t-bast** [comment]
What I ended up doing was a protector that was configured with an ACL (of multiaddrs) and the ACL could be externally controlled (via a channel) by a higher-level voting protocol to add/remove participants.
You can see the code [here](https://github.com/stratumn/go-node/tree/v0.1.0/core/protector) but the voting protocol is outside the protector which will make it hard to extract.
I don't like this current solution mainly because I'd like the ACL to use PeerIDs and not multiaddr. Unfortunately the pnet operates at a lower level where transport security isn't negotiated so it doesn't have access to RemotePeerID. 
I plan on re-writing that to protect at the transport-upgrader level and filter on a PeerID ACL.
I'll also change the voting protocol, so it's a big WIP right now :)
