### ISSUE TITLE
Finalize UX

### ISSUE THREAD

**Issue by Kubuxu** [libp2p/go-libp2p-pnet#4]
Tasks:
  - [x] print PNet key fingerprint when go-ipfs is starting
  - [x] tool for PNet key generation in go-ipfs
  - [x] useful notification if there are no peers because of PNet

@jbenet Is there anything else you would like to see?
@flyingzumwalt you might also want  to see something in here.
@hsanjuan I know you want to use PNet, anything you need?

**Comment by hsanjuan** [comment]
@Kubuxu the answer to `I have a libp2p-based service. How do I make it use PNet so that my only my nodes can talk to each other?`
