### ISSUE TITLE
Publish the spec document

### ISSUE THREAD

**Issue by Kubuxu** [libp2p/go-libp2p-pnet#6]

**Comment by cs145442** [comment]
Hi. It may not be priority but If documentation is taking time, some example code in the repo or some guidance to example in other repo will be appreciated. Thanks.

**Comment by Kubuxu** [comment]
Hey, here is the old writeup about pnet from few years ago, I think it is still accurate: https://gist.github.com/Kubuxu/b96b64be00ef949c8d486fe6e6bfc43e

**Comment by marten-seemann** [comment]
@50gramx There's a spec in https://github.com/libp2p/specs/blob/master/pnet/Private-Networks-PSK-V1.md. Is it not sufficient?

**Comment by Kubuxu** [comment]
Oh, it is the same document, I ended up publishing it after all. Closing.
